### ISSUE TITLE
9.5 build error

### ISSUE THREAD

**Issue by devrimgunduz** [ossc-db/pg_bulkload#1]
Hi,

I am getting these while building 3.1.8 against PostgreSQL 9.5:

gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_ADJ=0 -fpic -I../include -I/usr/pgsql-9.5/include -I. -I./ -I/usr/pgsql-9.5/include/server -I/usr/pgsql-9.5/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o source.o source.c
pg_btree.c:47:2: error: #error unsupported PostgreSQL version
 #error unsupported PostgreSQL version
  ^
pg_btree.c:100:42: error: unknown type name 'BTWriteState'
 static void _bt_mergeload(Spooler *self, BTWriteState *wstate, BTSpool *btspool,
                                          ^
pg_btree.c: In function 'SpoolerOpen':
pg_btree.c:132:2: error: too few arguments to function 'ExecOpenIndices'
  ExecOpenIndices(self->relinfo);
  ^
In file included from pg_btree.c:19:0:
/usr/pgsql-9.5/include/server/executor/executor.h:366:13: note: declared here
 extern void ExecOpenIndices(ResultRelInfo *resultRelInfo, bool speculative);
             ^
pg_btree.c: In function 'IndexSpoolBegin':
pg_btree.c:211:13: error: dereferencing pointer to incomplete type 'BTSpool {aka struct BTSpool}'
    spools[i]->isunique = indices[i]->rd_index->indisunique;
             ^
pg_btree.c: In function 'IndexSpoolEnd':
pg_btree.c:247:4: error: too few arguments to function 'reindex_index'
    reindex_index(indexOid, false);
    ^
In file included from pg_btree.c:18:0:
/usr/pgsql-9.5/include/server/catalog/index.h:117:13: note: declared here
 extern void reindex_index(Oid indexId, bool skip_constraint_checks,
             ^
pg_btree.c: In function 'IndexSpoolInsert':
pg_btree.c:343:14: warning: passing argument 1 of '_bt_spool' from incompatible pointer type [-Wincompatible-pointer-types]
    _bt_spool(itup, spools[i]);
              ^
In file included from pg_btree.c:15:0:
/usr/pgsql-9.5/include/server/access/nbtree.h:748:13: note: expected 'BTSpool * {aka struct BTSpool *}' but argument is of type 'IndexTuple {aka struct IndexTupleData *}'
 extern void _bt_spool(BTSpool *btspool, ItemPointer self,
             ^
pg_btree.c:343:20: warning: passing argument 2 of '_bt_spool' from incompatible pointer type [-Wincompatible-pointer-types]
    _bt_spool(itup, spools[i]);
                    ^
In file included from pg_btree.c:15:0:
/usr/pgsql-9.5/include/server/access/nbtree.h:748:13: note: expected 'ItemPointer {aka struct ItemPointerData *}' but argument is of type 'BTSpool * {aka struct BTSpool *}'
 extern void _bt_spool(BTSpool *btspool, ItemPointer self,
             ^
pg_btree.c:343:4: error: too few arguments to function '_bt_spool'
    _bt_spool(itup, spools[i]);
    ^
In file included from pg_btree.c:15:0:
/usr/pgsql-9.5/include/server/access/nbtree.h:748:13: note: declared here
 extern void _bt_spool(BTSpool *btspool, ItemPointer self,
             ^
pg_btree.c: In function '_bt_mergebuild':
pg_btree.c:359:2: error: unknown type name 'BTWriteState'
  BTWriteState wstate;
  ^
pg_btree.c:367:8: error: request for member 'index' in something not a structure or union
  wstate.index = btspool->index;
        ^
pg_btree.c:375:8: error: request for member 'btws_use_wal' in something not a structure or union
  wstate.btws_use_wal = self->use_wal &&
        ^
pg_btree.c:376:3: warning: implicit declaration of function 'XLogIsNeeded' [-Wimplicit-function-declaration]
   XLogIsNeeded() && !RELATION_IS_LOCAL(wstate.index);
   ^
In file included from /usr/pgsql-9.5/include/server/storage/lmgr.h:20:0,
                 from pg_btree.c:21:
pg_btree.c:376:46: error: request for member 'index' in something not a structure or union
   XLogIsNeeded() && !RELATION_IS_LOCAL(wstate.index);
                                              ^
/usr/pgsql-9.5/include/server/utils/rel.h:453:4: note: in definition of macro 'RELATION_IS_LOCAL'
  ((relation)->rd_islocaltemp || \
    ^
pg_btree.c:376:46: error: request for member 'index' in something not a structure or union
   XLogIsNeeded() && !RELATION_IS_LOCAL(wstate.index);
                                              ^
/usr/pgsql-9.5/include/server/utils/rel.h:454:4: note: in definition of macro 'RELATION_IS_LOCAL'
   (relation)->rd_createSubid != InvalidSubTransactionId)
    ^
pg_btree.c:383:8: error: request for member 'btws_pages_alloced' in something not a structure or union
  wstate.btws_pages_alloced = BTREE_METAPAGE + 1;
        ^
pg_btree.c:384:8: error: request for member 'btws_pages_written' in something not a structure or union
  wstate.btws_pages_written = 0;
        ^
pg_btree.c:385:8: error: request for member 'btws_zeropage' in something not a structure or union
  wstate.btws_zeropage = NULL; /* until needed */
        ^
pg_btree.c:392:21: error: request for member 'index' in something not a structure or union
  LockRelation(wstate.index, AccessExclusiveLock);
                     ^
pg_btree.c:393:29: error: request for member 'index' in something not a structure or union
  FlushRelationBuffers(wstate.index);
                             ^
pg_btree.c:396:38: error: request for member 'index' in something not a structure or union
  merge = BTReaderInit(&reader, wstate.index);
                                      ^
In file included from /usr/pgsql-9.5/include/server/postgres.h:48:0,
                 from ../include/pg_bulkload.h:9,
                 from pg_btree.c:11:
pg_btree.c:399:33: error: request for member 'index' in something not a structure or union
   RelationGetRelationName(wstate.index),
                                 ^
/usr/pgsql-9.5/include/server/utils/elog.h:212:23: note: in definition of macro 'elog'
   elog_finish(elevel, __VA_ARGS__); \
                       ^
/usr/pgsql-9.5/include/server/utils/rel.h:366:3: note: in expansion of macro 'NameStr'
  (NameStr((relation)->rd_rel->relname))
   ^
pg_btree.c:399:3: note: in expansion of macro 'RelationGetRelationName'
   RelationGetRelationName(wstate.index),
   ^
pg_btree.c:401:9: error: request for member 'btws_use_wal' in something not a structure or union
   wstate.btws_use_wal ? "with" : "without");
         ^
/usr/pgsql-9.5/include/server/utils/elog.h:212:23: note: in definition of macro 'elog'
   elog_finish(elevel, __VA_ARGS__); \
                       ^
pg_btree.c:404:34: error: request for member 'index' in something not a structure or union
  RelationSetNewRelfilenode(wstate.index, InvalidTransactionId);
                                  ^
pg_btree.c:404:2: error: too few arguments to function 'RelationSetNewRelfilenode'
  RelationSetNewRelfilenode(wstate.index, InvalidTransactionId);
  ^
In file included from /usr/pgsql-9.5/include/server/access/genam.h:21:0,
                 from pg_btree.c:13:
/usr/pgsql-9.5/include/server/utils/relcache.h:98:13: note: declared here
 extern void RelationSetNewRelfilenode(Relation relation, char persistence,
             ^
pg_btree.c:410:3: warning: implicit declaration of function '_bt_mergeload' [-Wimplicit-function-declaration]
   _bt_mergeload(self, &wstate, btspool, &reader, heapRel);
   ^
pg_btree.c:417:3: warning: implicit declaration of function '_bt_load' [-Wimplicit-function-declaration]
   _bt_load(&wstate, btspool, NULL);
   ^
pg_btree.c: At top level:
pg_btree.c:428:30: error: unknown type name 'BTWriteState'
 _bt_mergeload(Spooler *self, BTWriteState *wstate, BTSpool *btspool, BTReader *btspool2, Relation heapRel)
                              ^
pg_btree.c:38:13: warning: 'unused_bt_spooldestroy' declared 'static' but never defined [-Wunused-function]
 static void unused_bt_spooldestroy(BTSpool *);
             ^
pg_btree.c:39:13: warning: 'unused_bt_spool' declared 'static' but never defined [-Wunused-function]
 static void unused_bt_spool(IndexTuple, BTSpool *);
             ^
pg_btree.c:40:13: warning: 'unused_bt_leafbuild' declared 'static' but never defined [-Wunused-function]
 static void unused_bt_leafbuild(BTSpool *, BTSpool *);
             ^
pg_btree.c:626:1: warning: 'BTSpoolGetNextItem' defined but not used [-Wunused-function]
 BTSpoolGetNextItem(BTSpool *spool, IndexTuple itup, bool *should_free)
 ^
pg_btree.c:794:1: warning: 'BTReaderGetNextItem' defined but not used [-Wunused-function]
 BTReaderGetNextItem(BTReader *reader)
 ^
pg_btree.c:846:1: warning: 'compare_indextuple' defined but not used [-Wunused-function]
 compare_indextuple(const IndexTuple itup1, const IndexTuple itup2,
 ^
pg_btree.c:912:1: warning: 'heap_is_visible' defined but not used [-Wunused-function]
 heap_is_visible(Relation heapRel, ItemPointer htid)
 ^
pg_btree.c:926:1: warning: 'remove_duplicate' defined but not used [-Wunused-function]
 remove_duplicate(Spooler *self, Relation heap, IndexTuple itup, const char *relname)
 ^
<builtin>: recipe for target 'pg_btree.o' failed
make[2]: *** [pg_btree.o] Error 1
make[2]: *** Waiting for unfinished jobs....
reader.c: In function 'CheckerInit':
reader.c:433:16: error: 'RangeTblEntry {aka struct RangeTblEntry}' has no member named 'modifiedCols'
             rte->modifiedCols = bms_add_member(rte->modifiedCols, i);
                ^
reader.c:433:51: error: 'RangeTblEntry {aka struct RangeTblEntry}' has no member named 'modifiedCols'
             rte->modifiedCols = bms_add_member(rte->modifiedCols, i);
                                                   ^
<builtin>: recipe for target 'reader.o' failed
make[2]: *** [reader.o] Error 1
make[2]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/9.5/pg_bulkload/F-22/pg_bulkload-VERSION3_1_8/lib'
Makefile:27: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/9.5/pg_bulkload/F-22/pg_bulkload-VERSION3_1_8'
error: Bad exit status from /var/tmp/rpm-tmp.9l7FIc (%build)

**Comment by bwtakacy** [comment]
Hi,

Thanks for reporting.

The pg_bulkload 3.1.8 does not support PostgreSQL 9.5 because this was released on this February.
Now, we are developing VERSION3_1_STABLE branch to support 9.5 but have not released new version yet.

Could you try to use the latest source code of VERSION3_1_STABLE ?
We have confirmed this can be bulit with 9.5.
Honestly say, we have not tested for all the new features of 9.5 yet...
If you find some errors, please let us know.

Regards,

**Comment by theory** [comment]
Would love to see a new release supporting 9.5.

**Comment by bwtakacy** [comment]
Sorry for late.
We have finally released 3.1.9 which works with 9.5.

Thank you:)

**Comment by theory** [comment]
Awesome. Will you be releasing it in PGXN, as well?

**Comment by bwtakacy** [comment]
Yeah.

I will do it in this weekend.

**Comment by theory** [comment]
:+1:

**Comment by bwtakacy** [comment]
I did it. :sunglasses:

**Comment by theory** [comment]
Thanks!
